Nuptial/Controllers/CoupleController.cs
using Nuptial.Data;
using Nuptial.Models;
using Nuptial.Services;
using System.Web.Mvc;

namespace Nuptial.Controllers
{
    public class CoupleController : Controller
    {
        Context context = new Context();
        CoupleService service;

        public CoupleController()
        {
            service = new CoupleService(new Data.Repository.CoupleRepository(context));
        }
        // GET: Couple
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult CoupleHome()
        {
            BrideModel bride = BrideModel.Instance;
            GroomModel groom = GroomModel.Instance;

            var couple = service.GetNew();
            couple.Groom = groom.groom;
            couple.Bride = bride.bride;

            return PartialView("_Couple", couple);
        }
    }
}

Nuptial/Controllers/HeroBannerController.cs
using Nuptial.Data;
using Nuptial.Models;
using Nuptial.Services;
using System.Web.Mvc;

namespace Nuptial.Controllers
{
    public class HeroBannerController : Controller
    {
        Context context = new Context();
        HeroBannerService service;

        public HeroBannerController()
        {
            service = new HeroBannerService(new Data.Repository.HeroBannerRepository(context));
        }

        // GET: HeroBanner
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Home()
        {
            var model = service.GetHeroBanner(Data.Models.EnumPage.Home);
            return PartialView("_HeroBanner", model);
        }

        public PartialViewResult GroomBride()
        {
            var model = service.GetHeroBanner(Data.Models.EnumPage.GroomBride);
            return PartialView("_HeroBanner", model);
        }
    }
}

Nuptial/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Nuptial.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Nuptial/Views/Home/Index.cshtml
<div id="fh5co-page">
    @{ Html.RenderAction("Home", "HeroBanner"); }
    <header id="fh5co-header-section" class="sticky-banner">
        <div class="container">
            <div class="nav-header">
                <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
                <h1 id="fh5co-logo"><a href="index.html">Nuptial</a></h1>
                <!-- START #fh5co-menu-wrap -->
                <nav id="fh5co-menu-wrap" role="navigation">
                    <ul class="sf-menu" id="fh5co-primary-menu">
                        <li class="active"><a href="#">Home</a></li>
                        <li>
                            <a href="../GroomBride" class="fh5co-sub-ddown">Groom &amp; Bride</a>
                            <ul class="fh5co-sub-menu">
                                <li><a href="#">Dropdown Menu 1</a></li>
                                <li><a href="#">Dropdown Menu 2</a></li>
                                <li><a href="#">Dropdown Menu 3</a></li>
                                <li><a href="#">Dropdown Menu 4</a></li>
                            </ul>
                        </li>
                        <li><a href="when-where.html">When &amp; Where</a></li>
                        <li><a href="guest.html">Guest</a></li>
                        <li><a href="gallery.html">Gallery</a></li>
                        <li><a href="blog.html">Blog</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <!-- end:header-top -->

    @{ Html.RenderAction("CoupleHome", "Couple"); }


    <div id="fh5co-countdown">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center animate-box">
                <p class="countdown">
                    <span id="days"></span>
                    <span id="hours"></span>
                    <span id="minutes"></span>
                    <span id="seconds"></span>
                </p>
            </div>
        </div>
    </div>
    <div id="fh5co-started" style="background-image:url(../../images/cover_bg_2.jpg);" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row animate-box">
                <div class="col-md-8 col-md-offset-2 text-center heading-section">
                    <h2>Are You Attending?</h2>
                    <p>Please Fill-up the form to notify you that you're attending. Thanks.
                </div>
            </div>
            <div class="row animate-box">
                <div class="col-md-10 col-md-offset-1">
                    <form class="form-inline">
                        <div class="col-md-4 col-sm-4">
                            <div class="form-group">
                                <label for="name" class="sr-only">Name</label>
                                <input type="name" class="form-control" id="name" placeholder="Name">
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-4">
                            <div class="form-group">
                                <label for="email" class="sr-only">Email</label>
                                <input type="email" class="form-control" id="email" placeholder="Email">
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-4">
                            <button type="submit" class="btn btn-primary btn-block">I am Attending</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>